### ISSUE TITLE
Not able to transform 'للا' to utf8 format

### ISSUE THREAD

**Issue by tabish-kook** [khaled-alshamaa/ar-php#65]
Hello @khaled-alshamaa ,

Hope you are doing great. Your project is awesome and helping us a lot, but I am facing a problem with "للإ" letter.

Here is the code which I have used to transform html to utf8 format to then provide to dompdf to generate a pdf.

```php
$invoiceHtml = view('invoice', $invoiceData)->render();
$arabic = new Arabic();
$p = $arabic->arIdentify($invoiceHtml);
for ($i = count($p) - 1; $i >= 0; $i -= 2) {
      $utf8ar = $arabic->utf8Glyphs(substr($invoiceHtml, $p[$i - 1], $p[$i] - $p[$i - 1]), 50, false);
      $invoiceHtml = substr_replace($invoiceHtml, $utf8ar, $p[$i - 1], $p[$i] - $p[$i - 1]);
}
``` 

The text line having a problem:

`شركة مكتب للإستشارات الهندسية
`

Output after applying the above code:

`مكتب لإxFE#&ستشارات الهندسية شركة`

By looking into the output, the issue seems to be with the letter "للإ" apprarently , but you can tell better.

I would really appreciate if you can look into it asap as we need to send invoices to our clients and we are stuck with this problem at the moment.

Thanks in advance.

**Comment by khaled-alshamaa** [comment]
Hi @tabish-kook,

Which version of Ar-PHP library you are using? A similar bug has been fixed in the very latest version 6.3.4 (check related [changelog announcement](https://github.com/khaled-alshamaa/ar-php/blob/master/CHANGELOG.md#whats-new-in-arphp-634-release-date-apr-5-2023)). So, please make sure that you are using the very latest version.

On the other hand, there is no need anymore to handle the Arabic fragments in your code flow outside the utf8Glyphs call to take care of bidi logic. In other words, your code snippet can be simplified as the following:

```php
$arabic = new Arabic();
$invoiceHtml = view('invoice', $invoiceData)->render();
$invoiceHtml = $arabic->utf8Glyphs($invoiceHtml);
```

Finally, just for curiosity, which application are you using? Or it is a customized script? Also, the `$invoiceHtml` output, is it rendered using dompdf?

**Comment by tabish-kook** [comment]
Thanks for the quick response, we are using 6.3.1 version and its a laravel application, and yes generating the pdf via domPdf. Will update the version to the latest one as you mentioned.

**Comment by tabish-kook** [comment]
Hey @khaled-alshamaa 

I have update the version to 6.3.4 and the issue has been resolved. Thanks a lot.

**Comment by khaled-alshamaa** [comment]
You are most welcome! I am always happy to help :-)
