### ISSUE TITLE
Issue with ar-php and latest libgd with libraqm0

### ISSUE THREAD

**Issue by AymanFekri** [khaled-alshamaa/ar-php#76]
Thank you for this great library! I'm having an issue with Arabic text ordering when using the latest libgd with libraqm0.  It works fine with older libgd versions without raqm

**To Reproduce**
1. Install latest libgd with libraqm0.
2. Use the code from the ar-php example [pages](https://gist.github.com/AymanFekri/96ae2cc3b8edd1c99ee524d32e41c150).

**Expected behavior**
Correct Arabic text order, regardless of libraqm0.

**Screenshot**
![telegram-cloud-photo-size-4-5821203858033066656-x](https://github.com/user-attachments/assets/719a0c95-b58d-40db-8863-c32b39539fcc)

**Environment:**
* PHP: 8.1
* libgd3 | 2.3.3-12+ubuntu22.04.1+deb.sury.org+1
* OS: Ubuntu 22.04

Downgrading libgd to a version without libraqm0 fixes the issue, but I'd really like to use the latest version if possible. Is there any way to fix this? Thanks again!

**Comment by khaled-alshamaa** [comment]
Dear @AymanFekri, thanks for reporting this :-)

If your GD library includes [libraqm](https://github.com/HOST-Oman/libraqm) support, there is no need to preprocess your Arabic script using the `utf8Glyphs()` function (see how the first line in the example screenshot renders correctly). Applying `utf8Glyphs()` in this case would reverse the letters order twice (once through our function and again through Raqm's internal processing), resulting in incorrect left-to-right rendering.

Therefore, there is no need to downgrade your setup. Simply skip the preprocessing step with `utf8Glyphs()` and pass your Arabic text directly to GD library functions like `imagettftext()`.

At Ar-PHP library, we will not modify the behavior of the `utf8Glyphs()` function because it is designed to be generic and flexible for various use cases. GD is just one potential context; others might involve PDF rendering, etc.

I will highly appreciate it if you can please share the output of the following PHP command from your server setup:
```php
var_dump(gd_info());
```
While I am not certain how `libraqm` support will appear in this array, once I see the output, I can help you apply a conditional check like this:
```php
if (!gd_info()['RAQM Support'] ?? false) {
    $text = $Arabic->utf8Glyphs($text);
}
```
@khaledhosny, can you advise please ;-)

**Comment by khaledhosny** [comment]
It does not look like `gd_info()` provide anything about Raqm support. I no nothing about PHP, but `gd_info()` [source code](https://github.com/php/php-src/blob/d8d388eb3a1e4a8281be52e5fcc8e8fa20d6f75d/ext/gd/gd.c#L464) and [its documentation](https://www.php.net/manual/en/function.gd-info.php) have no mention of Raqm at all.

**Comment by AymanFekri** [comment]
Dear @khaled-alshamaa 

Thank you so much for your prompt and detailed response! I appreciate you taking the time to explain the interaction between `utf8Glyphs()` and libraqm.

I checked the output of `var_dump(gd_info());` as you suggested, and it doesn't seem to provide any explicit information about libraqm support:

```php
$ php -r 'var_dump(gd_info());'
array(15) {
  ["GD Version"]=>
  string(5) "2.3.3"
  ["FreeType Support"]=>
  bool(true)
  ["FreeType Linkage"]=>
  string(13) "with freetype"
  ["GIF Read Support"]=>
  bool(true)
  ["GIF Create Support"]=>
  bool(true)
  ["JPEG Support"]=>
  bool(true)
  ["PNG Support"]=>
  bool(true)
  ["WBMP Support"]=>
  bool(true)
  ["XPM Support"]=>
  bool(true)
  ["XBM Support"]=>
  bool(true)
  ["WebP Support"]=>
  bool(true)
  ["BMP Support"]=>
  bool(true)
  ["AVIF Support"]=>
  bool(true)
  ["TGA Read Support"]=>
  bool(true)
  ["JIS-mapped Japanese Font Support"]=>
  bool(false)
}
```

It appears that libraqm support is enabled by default in the libgd package for Ubuntu, even though it's not strictly required for GD. 

In the meantime, I'm going to build libgd without libraqm to ensure compatibility with `utf8Glyphs()`.

Thanks again for your help!

Best regards,

Ayman

**Comment by khaledhosny** [comment]
With Raqm support enabled, you get vastly superior Arabic support (it works with more fonts, you get like gatures, mark positioning and many other OpenType features, etc.). If you control what system your code runs on, I suggest you drop use of `utf8Glyphs` and rely on Raqm for Arabic support.

**Comment by khaled-alshamaa** [comment]
Well, thanks for your trust @AymanFekri, but if I were in your shoes, I will follow @khaledhosny advice as Raqm support covering a wider range of issues exceeds what we have in Ar-PHP library. Therefore, if the software is yours, you may add some configuration to tell if the hosting server has Raqm support or not, and upon that setting, your code may preprocess Arabic strings using utf8Glyphs or not before pass it to any GD library function.

@khaledhosny, it will be great to contribute to improve the gd_info() function by adding Raqm flag in their response. Please let me know if you need any support or use case to clarify the need and usage of such case in the PHP context, we will be more than happy to collaborate with Raqm development team in that 🤗

**Comment by khaledhosny** [comment]
I don’t really know much about PHP to be of any help here, sorry.
